### ISSUE TITLE
Does not work with https://hyperwizard.azurewebsites.net/hywit/void

### ISSUE THREAD

**Issue by pke** [stephenwright/shipwreck#36]
It fails to fetch this API, which returns a proper SIREN response.
The server responds 406 when using your tool, but using curl and requesting the SIREN content type works fine.

**Comment by stephenwright** [comment]
Looks to me like the request is being blocked by the server because of Cross Origin Resouce Sharing

**Comment by pke** [comment]
hmm... missing CORS headers?

**Comment by stephenwright** [comment]
did that fix it for you?
